theme: jekyll-theme-minimal
title: Immigrants and Gang Databases Amdendment
description: A draft amendment to an AFT Resolution against attacks on immigrants.
logo: /assets/img/dont-deport.jpg
plugins:
  - jekyll-seo-tag
twitter:
  card: summary_large_image
  username: goldnate
