theme: jekyll-theme-minimal
title: Red Hootenanny at S'18
description: Labor and movement songs for socialists to sing and celebrate
logo: /assets/img/red-hootenanny.png
plugins:
  - jekyll-seo-tag
twitter:
  card: summary_large_image
  username: goldnate
