theme: jekyll-theme-minimal
title: Red Hootenanny at S'18
description: Lyrics for songs to sing in the lobby by the Haymarket books room on Thursday, July 5 after the day's last workshop at the Socialism 2018 Conference.
logo: /assets/img/red-hootenanny.png
plugins:
  - jekyll-seo-tag
twitter:
  card: summary_large_image
  username: goldnate
