theme: jekyll-theme-minimal
title: Red Hootenanny at S'18
description: Lyrics for songs to sing on the hotel lawn at the Socialism 2018 Conference on Thursday, July 5 after the last workshop.
logo: /assets/img/red-hootenanny.png
plugins:
  - jekyll-seo-tag
twitter:
  card: summary_large_image
  username: goldnate
