theme: jekyll-theme-minimal
title: Red Hootenanny at S'18
description: Lyrics for songs to sing on the hotel patio at the Socialism 2018 Conference: Thursday, July 5 at 9:30pm.
logo: /assets/img/red-hootenanny.png
plugins:
  - jekyll-seo-tag
twitter:
  card: summary_large_image
  username: goldnate
